### PR TITLE
Make UI more responsive (Make it look better)

### PR DESCRIPTION
**Pull request by Borjianamin98**
all of changes in this pull request related to change in UI to make it look better (include help, license, properties dialog and etc)

### CODE REVIEW

**Comment by IYP-Programer-Yeah** [comment]
commits up to `Fix fxml to use new path for their controller`  : b8aacc43e6ee86faef6114c06f07e8a291cd118d are already merged and squashed. Please rebase new commits on an up to date branch with current master.

**Comment by Borjianamin98** [comment]
> 
> 
> commits up to `Fix fxml to use new path for their controller` : [b8aacc4](https://github.com/IYP-Programer-Yeah/PGen/commit/b8aacc43e6ee86faef6114c06f07e8a291cd118d) are already merged and squashed. Please rebase new commits on an up to date branch with current master.

Thanks. I don't know how to do that. I tried but my last commits showed again. What should I do?

**Comment by IYP-Programer-Yeah** [comment]
> > commits up to `Fix fxml to use new path for their controller` : [b8aacc4](https://github.com/IYP-Programer-Yeah/PGen/commit/b8aacc43e6ee86faef6114c06f07e8a291cd118d) are already merged and squashed. Please rebase new commits on an up to date branch with current master.
> 
> Thanks. I don't know how to do that. I tried but my last commits showed again. What should I do?

Use `git rebase HEAD~20 -i`. This is an interactive rebase, and will allow you to choose the commits you want and drop the ones you dont. I had a try at it and it seems to have worked, take a look at the branch [make things work](https://github.com/IYP-Programer-Yeah/PGen/tree/maket-things-work). Try to rebase yourself, and make an other merge request. It will also be of help to make a branch for your changes on your side, and make a merge request after, to avoid invalidating your own master.

**Comment by IYP-Programer-Yeah** [comment]
Still having problem with this?

**Comment by Borjianamin98** [comment]
> 
> 
> Still having problem with this?

Yes. I do it and try it with different approach, but it is not work. besides, because of my new work, I have less time to work on it. Is it good to fork it again and do all last commits?

**Comment by IYP-Programer-Yeah** [comment]
You can do it that way if you find that easier, however, my recommendation is to do it with interactive rebase, contact me either with my email, or my telegram if you needed any help with the process.

**Pull request closed without merging**
